import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_ce_flutter/hive_ce_flutter.dart'; //
import 'package:tictacgo/app.dart';
import 'package:tictacgo/features/game/domain/game_stats.dart'; //

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // init hive
  await Hive.initFlutter();

  // Register the adapter for GameStats (generated by build_runner)
  Hive.registerAdapter(GameStatsAdapter());

  // Open the box to store the scores
  await Hive.openBox<GameStats>('stats_box');

  runApp(const ProviderScope(child: TicTacGoApp()));
}
